name: libcmark_gfm
options:
  bundleIdPrefix: com.pepas
targets:
  libcmark_gfm:
    type: framework
    platform: iOS
    deploymentTarget: "15.6"
    scheme: {}
    sources: [src, extensions]
    settings:
      GENERATE_INFOPLIST_FILE: YES
